theme = "solarized_dark"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space.t]
s   = ":toggle soft-wrap.enable"

[editor.soft-wrap]
enable = true
